name: build-version-ubuntu
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  workflow_call:
  
jobs:
  build:  
    runs-on: ubuntu-latest
    env:
      # BUILD_PATH: angular-conduit
      SOURCE_PATH: dist/angular-conduit
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    #node block
      - name: Use Node.js Version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      #Running commands inside the node conatiner
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install
      
      - name: Angular Code Build
        run: ng build 

      - name: Get Project Version from package.json
        run: |
          projectVersion=$(cat package.json | grep -o '"version": *"[^"]*' | awk -F'"' '{ print $4 }')
          echo "PROJECT_VERSION=$projectVersion" >> $GITHUB_ENV
       
      - name: Construct the final build version
        run: |
          echo "The Project Version from package.json is ${{env.PROJECT_VERSION}}"
          echo "The build number is ${{github.run_number}}"
          buildVersion=${{env.PROJECT_VERSION}}-${{github.run_number}}
          echo "BUILD_VERSION=$buildVersion" >> $GITHUB_ENV
                      
      # - name: Create Build Directory
      #   run: mkdir ${{ env.FORM-EDITOR_BUILD_PATH}}/angular-hello-world_${{ env.BUILD_VERSION }}/angular-hello-world_${{ env.BUILD_VERSION }}
      
      - name: Compress Files
        run: zip -r  "${{ env.SOURCE_PATH }}.${{ env.BUILD_VERSION }}.zip" "${{ env.SOURCE_PATH }}"/*
        
      # - run : mv ${{ env.FORM-EDITOR_SOURCE_PATH}}/* ${{ env.FORM-EDITOR_BUILD_PATH}}/angular-hello-world_${{ env.BUILD_VERSION }}/angular-hello-world_${{ env.BUILD_VERSION }} 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: "${{ env.SOURCE_PATH }}.${{ env.BUILD_VERSION }}.zip"




# name: Build

# on:
#   # push:
#   #   branches:  
#   #     - main
#   workflow_call:
#   workflow_dispatch:
#     inputs:
#       node-version:
#         description: Optionally pass the Node version. Default value is 12.x
#         required: false
#         type: string
#         default: 18.x

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#           registry-url: 'https://npm.pkg.github.com'
#           # Defaults to the user or organization that owns the workflow file
#           scope: '@devilhunter4444'
    
#       # - name: Configure npm registry for GitHub Packages
#       #   run: npm config set registry https://npm.pkg.github.com/

#       - name: Get Project Version from package.json
#         run: |
#           projectVersion=$(cat package.json | grep -o '"version": *"[^"]*' | awk -F'"' '{ print $4 }')
#           echo "PROJECT_VERSION=$projectVersion" >> $GITHUB_ENV

#       - name: Construct the final build version
#         run: |
#           echo "The Project Version from package.json is ${{ env.PROJECT_VERSION }}"
#           echo "The build number is ${{ github.run_number }}"
#           buildVersion=${{ env.PROJECT_VERSION }}-${{ github.run_number }}
#           echo "BUILD_VERSION=$buildVersion" >> $GITHUB_ENV

#       - name: Bump version
#         run: npm --git-tag-version=false version ${{env.BUILD_VERSION}}

#       - run: npm install -g @angular/cli 
#       - run: npm install
      
#       - name: Build
#         run: ng build

#       # - name: Copy build files to dist
#       #   run: cp -r ./dist/new-angular/app/* ./dist/

#       - name: Publish to GitHub Packages
#         run: |
#             npm publish 
#         env:
#             NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      



